# Generated by Django 4.1.2 on 2022-11-02 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='message',
        ),
    ]
